// Code generated by "stringer -type=Region -linecomment"; DO NOT EDIT.

package blizzard

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[US-1]
	_ = x[EU-2]
	_ = x[KR-3]
	_ = x[TW-4]
	_ = x[CN-5]
}

const _Region_name = "useukrtwcn"

var _Region_index = [...]uint8{0, 2, 4, 6, 8, 10}

func (i Region) String() string {
	i -= 1
	if i < 0 || i >= Region(len(_Region_index)-1) {
		return "Region(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Region_name[_Region_index[i]:_Region_index[i+1]]
}
