/*
 * @Author: Allen Flickinger (allen.flickinger@gmail.com)
 * @Date: 2018-01-07 12:38:20
 * @Last Modified by: FuzzyStatic
 * @Last Modified time: 2018-01-14 22:13:23
 */

package worldofwarcraft

const (
	abilityPath        = "/ability"
	achievementPath    = "/achievement"
	auctionDataPath    = "/auction/data"
	bossPath           = "/boss"
	challengePath      = "/challenge"
	characterPath      = "/character"
	connectedRealmPath = "/connected-realm"
	guildPath          = "/guild"
	itemPath           = "/item"
	mountPath          = "/mount"
	mythicLeaderPath   = "/mythic-leaderboard"
	periodPath         = "/period"
	petPath            = "/pet"
	realmPath          = "/realm"
	regionPath         = "/region"
	statsPath          = "/stats"
	setPath            = "/set"
	speciesPath        = "/species"
	tokenPath          = "/token"
	accessTokenQuery   = "access_token="
	apiKeyQuery        = "apikey="
	breedIDQuery       = "breedId="
	fieldsQuery        = "fields="
	namespaceQuery     = "namespace="
	levelQuery         = "level="
	localeQuery        = "locale="
	qualityIDQuery     = "qualityId="
	achievementsField  = "achievements"
	appearanceField    = "appearance"
	auditField         = "audit"
	challengeField     = "challenge"
	feedField          = "feed"
	guildField         = "guild"
	hunterPetsField    = "hunterPets"
	itemsField         = "items"
	membersField       = "members"
	mountsField        = "mounts"
	newsField          = "news"
	petsField          = "pets"
	petSlotsField      = "petSlots"
	professionsField   = "professions"
	progressionField   = "progression"
	pvpField           = "pvp"
	questsField        = "quests"
	reputationField    = "reputation"
	statisticsField    = "statistics"
	statsField         = "stats"
	talentsField       = "talents"
	titlesField        = "titles"
)
